version: "3.8"

services:
  postgres-db:
    image: postgres
    container_name: eap_test_db
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    restart: unless-stopped
